const PERMISOS = {
    // Permisos de auditoría
    VER_AUDITORIA: 'VER_AUDITORIA',
    EXPORTAR_AUDITORIA: 'EXPORTAR_AUDITORIA',
    FILTRAR_AUDITORIA: 'FILTRAR_AUDITORIA',

    // Permisos de muestras
    CREAR_MUESTRA: 'CREAR_MUESTRA',
    EDITAR_MUESTRA: 'EDITAR_MUESTRA',
    ELIMINAR_MUESTRA: 'ELIMINAR_MUESTRA',
    VER_MUESTRAS: 'VER_MUESTRAS',

    // Permisos de resultados
    REGISTRAR_RESULTADOS: 'REGISTRAR_RESULTADOS',
    EDITAR_RESULTADOS: 'EDITAR_RESULTADOS',
    VER_RESULTADOS: 'VER_RESULTADOS',

    // Permisos de firmas
    FIRMAR_DOCUMENTO: 'FIRMAR_DOCUMENTO',
    VER_FIRMAS: 'VER_FIRMAS',

    // Permisos de cambios de estado
    CAMBIAR_ESTADO: 'CAMBIAR_ESTADO',
    VER_HISTORIAL: 'VER_HISTORIAL'
};

// Mapeo de roles a permisos
const ROLES_PERMISOS = {
    administrador: [
        PERMISOS.VER_AUDITORIA,
        PERMISOS.EXPORTAR_AUDITORIA,
        PERMISOS.FILTRAR_AUDITORIA,
        PERMISOS.CREAR_MUESTRA,
        PERMISOS.EDITAR_MUESTRA,
        PERMISOS.ELIMINAR_MUESTRA,
        PERMISOS.VER_MUESTRAS,
        PERMISOS.REGISTRAR_RESULTADOS,
        PERMISOS.EDITAR_RESULTADOS,
        PERMISOS.VER_RESULTADOS,
        PERMISOS.FIRMAR_DOCUMENTO,
        PERMISOS.VER_FIRMAS,
        PERMISOS.CAMBIAR_ESTADO,
        PERMISOS.VER_HISTORIAL
    ],
    laboratorista: [
        PERMISOS.VER_AUDITORIA,
        PERMISOS.CREAR_MUESTRA,
        PERMISOS.EDITAR_MUESTRA,
        PERMISOS.VER_MUESTRAS,
        PERMISOS.REGISTRAR_RESULTADOS,
        PERMISOS.EDITAR_RESULTADOS,
        PERMISOS.VER_RESULTADOS,
        PERMISOS.FIRMAR_DOCUMENTO,
        PERMISOS.VER_FIRMAS,
        PERMISOS.CAMBIAR_ESTADO,
        PERMISOS.VER_HISTORIAL
    ],
    cliente: [
        PERMISOS.VER_MUESTRAS,
        PERMISOS.VER_RESULTADOS,
        PERMISOS.FIRMAR_DOCUMENTO,
        PERMISOS.VER_FIRMAS,
        PERMISOS.VER_HISTORIAL
    ]
};

module.exports = {
    PERMISOS,
    ROLES_PERMISOS
}; 